name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - pip
  - xeus-python
  - anywidget
  - requests
  - pandas
  - plotnine
  - numpy
  - matplotlib
  - seaborn
  - folium
  - sqlite_utils
  - pip:
    - jupyterlite-simple-cors-proxy
    - requests-cache
    - attrs
    - cattrs
    - platformdirs
    - url-normalize